// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUnlFdA1ihvMGm7RKFghaw0mQIpJXuO9U',
    appId: '1:305506255355:android:4dfd57a9e899c7ff1ccb5e',
    messagingSenderId: '305506255355',
    projectId: 'Care4Her',
    storageBucket: 'Care4Her.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQMaRO3AsEnF6njtL9eNQiscBg3oMOmWk',
    appId: '1:305506255355:ios:46f5f535c3772c271ccb5e',
    messagingSenderId: '305506255355',
    projectId: 'Care4Her',
    storageBucket: 'Care4Her.firebasestorage.app',
    iosBundleId: 'com.asrafulislam.Care4Her',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEZ7EWnrFflGWPk-Hjy1hgWG7FyAh0DGA',
    appId: '1:305506255355:web:bb7dca80661678431ccb5e',
    messagingSenderId: '305506255355',
    projectId: 'Care4Her',
    authDomain: 'Care4Her.firebaseapp.com',
    storageBucket: 'Care4Her.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQMaRO3AsEnF6njtL9eNQiscBg3oMOmWk',
    appId: '1:305506255355:ios:46f5f535c3772c271ccb5e',
    messagingSenderId: '305506255355',
    projectId: 'Care4Her',
    storageBucket: 'Care4Her.firebasestorage.app',
    iosBundleId: 'com.asrafulislam.Care4Her',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEZ7EWnrFflGWPk-Hjy1hgWG7FyAh0DGA',
    appId: '1:305506255355:web:f4fb6f739e793bc01ccb5e',
    messagingSenderId: '305506255355',
    projectId: 'Care4Her',
    authDomain: 'Care4Her.firebaseapp.com',
    storageBucket: 'Care4Her.firebasestorage.app',
  );

}